### PR TITLE
Use Bundler for gem management

### PR DESCRIPTION
**Pull request by daxelrod**
Declare dependencies in Gemfile and modify instructions to use
Bundler. This will improve the reproducibility of the install
instructions.

This and other changes will make `slack-karmabot` eventually
deployable to Heroku or another platform-as-a-service #9 .

### CODE REVIEW

**Comment by arubinoff** [comment]
i don't know much about how ruby works, or bundler, but i'd like to keep the instructions compatible with running this locally on a server you own, not just on heroku. Does step 9 conflict with that?

**Comment by daxelrod** [comment]
> i'd like to keep the instructions compatible with running this locally on a server you own, not just on heroku

Absolutely! Use Case Number 1 is still @arubinoff hosting slackbot on her server.

Further, nothing in these instructions is intended to have anything Heroku-specific at all.

Is is the `$HOST` and `$PORT` parts you're worried about? I had intended those to be placeholders for values the user would put in themselves.

Would something like

> Run the server: `bundle exec rackup config.ru` and you're good to go! (Use the `-p` or `-o` flag to `rackup` to set a port or host, respectively.)

work better?

**Comment by arubinoff** [comment]
OK, I finally took a look at this and I think it should be good as is - I'm assuming the bundle exec command will set up/run the sinatra server for you.

Given that I'll merge this in, but let me know if I'm wrong haha.

**Comment by daxelrod** [comment]
> I'm assuming the bundle exec command will set up/run the sinatra server for you.

Correct! The `bundle install` command has installed all of the gems to you need to run karmabot into `vendor/`.

[`bundle exec`](http://bundler.io/man/bundle-exec.1.html) runs the command following it with gem paths set up to load from this `vendor/` directory.

[`rackup`](https://github.com/rack/rack/wiki/(tutorial)-rackup-howto) is a common way to run any server using the Rack middleware, including Sinatra.

**Pull request merged**
